### ISSUE TITLE
SVG Logo

### ISSUE THREAD

**Issue by blue-devil** [angr/angr-website-hugo#55]
Hello folks
Is it possible to provide an SVG logo of angr?
Thank you very much.

**Comment by rhelmot** [comment]
![angr](https://github.com/user-attachments/assets/c648bcc3-aac3-4f95-b67d-290b82fdc45f)
Behold, the angr.svg reproduction I built a few years ago after the original had been lost to time!

**Comment by blue-devil** [comment]
Thank you very much =)
